language: java
jdk:
  - oraclejdk8
  - oraclejdk7
deploy:
  - provider: pages
    github_token: 
        secure: oWQZmp45c6pbSC27rsLBeErtbwAASAsj14aav0ZQS417dS5xdLtP9EedKJgcBQMH7z4YcTlC8Vgk165YClZgsYNv15G4e6aAzLQDsIJt440ST0WYFS/tKHTmqUp4wQe9pmhAnQ0VjbUcqXgbb6onk0onL57JHEK+wd4zJiM3bvSrBbKKbwMIxGg2NuKS4CwjDy76I+PyDy6I75Btwi2IGU9zophPAE5Mz3+uZlDAqJUgDwvjd5oDqpWuuzxD4XegP2GZGdCOH9Yh2HyPU6HP0ZQr2p9LQcStxeFZha8YN1UPBtcCRHDva6aixBTOkRN9WGHHrPvK0A5745d7u7NavbzWHQ9Jy4Qm7QR8hhAocroRRL7oJeDQccidA5w3QoSpJTQ9O/zuRSBRog5pfXeTZHRUd0R4JRLsCVEYL5NdsSnsLeTjUW1wsM2vkxXwyulfCdSghIoGSYq4qFgzfaNg88zbWrKzPnHsuK09LP9tamGvhryh+vjXpS967oe3OWewrfUGUWR0T8FnGeV+6JELX7WEOEJt+FokmP4Jk3DOsi+AwvSIA9npGiVW6YlfB5meqooaCv45nWbg2DHwqLiyX/+VPpsHpf2zWsN+9BUZ+8/iajfc+yGsDydXaqg30PvJPfCSNInhR+y0qEDriYtLPjbjoHWGdi7p+YTbB2tcYKs=
    skip_cleanup: true
    on:
        branch: master
    local_dir: docs
  - provider: releases
    api_key:
        secure: oWQZmp45c6pbSC27rsLBeErtbwAASAsj14aav0ZQS417dS5xdLtP9EedKJgcBQMH7z4YcTlC8Vgk165YClZgsYNv15G4e6aAzLQDsIJt440ST0WYFS/tKHTmqUp4wQe9pmhAnQ0VjbUcqXgbb6onk0onL57JHEK+wd4zJiM3bvSrBbKKbwMIxGg2NuKS4CwjDy76I+PyDy6I75Btwi2IGU9zophPAE5Mz3+uZlDAqJUgDwvjd5oDqpWuuzxD4XegP2GZGdCOH9Yh2HyPU6HP0ZQr2p9LQcStxeFZha8YN1UPBtcCRHDva6aixBTOkRN9WGHHrPvK0A5745d7u7NavbzWHQ9Jy4Qm7QR8hhAocroRRL7oJeDQccidA5w3QoSpJTQ9O/zuRSBRog5pfXeTZHRUd0R4JRLsCVEYL5NdsSnsLeTjUW1wsM2vkxXwyulfCdSghIoGSYq4qFgzfaNg88zbWrKzPnHsuK09LP9tamGvhryh+vjXpS967oe3OWewrfUGUWR0T8FnGeV+6JELX7WEOEJt+FokmP4Jk3DOsi+AwvSIA9npGiVW6YlfB5meqooaCv45nWbg2DHwqLiyX/+VPpsHpf2zWsN+9BUZ+8/iajfc+yGsDydXaqg30PvJPfCSNInhR+y0qEDriYtLPjbjoHWGdi7p+YTbB2tcYKs=
    file_glob: true
    file: build/jar/*
    skip_cleanup: true
    on:
        tags: true